# Generated by Django 5.2.1 on 2025-05-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_clientdetails_aadhaar_clientdetails_joinedat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
