# Generated by Django 5.2.1 on 2025-05-19 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_client_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('aadhaar', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_aadhaar', message='Aadhaar number must be 12 digits long, should not start with 0 or 1, and should not contain any spaces or special characters', regex='^[2-9]{1}[0-9]{3}[0-9]{4}[0-9]{4}$')])),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('addedby', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renters_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joinedAt'],
            },
        ),
    ]
