# Generated by Django 5.2.1 on 2025-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='aadhaar',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
