# Generated by Django 5.2.1 on 2025-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_renter_address_renter_profile_pic_renter_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
