# Generated by Django 5.1.4 on 2025-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_review_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_scheduling',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
