# Generated by Django 5.2.1 on 2025-05-19 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0010_renter_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('SUV', 'Suv'), ('Scooter', 'Scooter'), ('Truck', 'Truck'), ('Other', 'Other')], max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'Cng')], max_length=10)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('mileage', models.FloatField(help_text='km per liter or km per charge')),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=30)),
                ('top_speed', models.PositiveIntegerField(blank=True, help_text='in km/h', null=True)),
                ('available', models.BooleanField(default=True)),
                ('location', models.TextField()),
                ('current_odometer', models.FloatField(help_text='in kilometers')),
                ('insurance_expiry_date', models.DateField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_1', models.TextField()),
                ('image_2', models.TextField()),
                ('image_3', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.renter')),
            ],
        ),
    ]
