# Generated by Django 5.2.1 on 2025-05-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
